In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
print(a.shape,a.ndim,a.dtype,np.linalg.matrix_rank(a))


(5,) 1 int32 1


In [3]:
b=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
c=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]],dtype='float32')
print(c)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [9]:
print(c.shape,c.ndim,c.dtype,np.linalg.matrix_rank(c))


(3, 4) 2 float32 2


In [13]:
A=np.array(3)
print(A)



3


In [14]:
A=np.arange(1,5)
A=A.reshape(2,2)
print(A)


[[1 2]
 [3 4]]


In [16]:
x=a
print(x)
print(x[0],x[:2],x[1:3])

[1 2 3 4 5]
1 [1 2] [2 3]


In [18]:
x[0]=-99
print(a)
x[0]=1

[-99   2   3   4   5]


In [19]:
x=b
print(x[0],x[:2],x[1:3],sep="\n")
print(x[:0],x[:2,0:2],x[1,0:2],sep="\n")
print(x[:0:1],x[:2,0:2],x[1:2,0:2],sep="\n")

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[]
[[1 2]
 [5 6]]
[5 6]
[]
[[1 2]
 [5 6]]
[[5 6]]


In [20]:
y=x[1:3,1:3]
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
x[0,0]=-99
print(x,b,sep="\n")

[[-99   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[-99   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [22]:
print(a)
print(a+2,a-2,a*2,a/2,sep="\n")

[1 2 3 4 5]
[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [23]:
np.add(0,2)
print(a.sum(),b.sum(axis=0),b.sum(axis=1))
print(np.sin(a),np.log(a))

15 [-85  18  21  24] [-90  26  42]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427] [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [24]:
A=np.ones((3,3))
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
A=np.zeros((3,4))
A


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
A=np.diag([1,2,3])
A

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [31]:
B=np.random.random((3,4))
print(B)

[[0.39570208 0.76691761 0.23543584 0.64632108]
 [0.11836731 0.29198487 0.58120951 0.21482052]
 [0.75182301 0.524549   0.65612544 0.31508975]]


In [32]:
x=np.array([1,2,3])
y=np.array([1,1,2])
print(x.dot(y))
print(x@y)

9
9


In [34]:
A=np.array([[1,2],[3,4]])
B=np.array([[1,0,1],[2,2,2]])
C=A.dot(B)
print(A,B,C,sep="\n")
C=A@B
print()

[[1 2]
 [3 4]]
[[1 0 1]
 [2 2 2]]
[[ 5  4  5]
 [11  8 11]]



In [36]:
A=np.array([[2,3],[3,-1]])
B=np.array([[1],[7]])
C=np.linalg.inv(A)@B
print(C)

[[ 2.]
 [-1.]]


In [38]:
x=np.insert(A,0,1,axis=-1)
x

array([[ 1,  2,  3],
       [ 1,  3, -1]])

In [40]:
x=np.insert(A,2,1,axis=0)
x


array([[ 2,  3],
       [ 3, -1],
       [ 1,  1]])

In [41]:
a=np.arange(3)
print(a)
print(a+5)

[0 1 2]
[5 6 7]


In [43]:
a=np.ones([3,3])
print(a)
b=np.arange(3)
print(b)
print(a+b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [45]:
a=np.arange(3).reshape(3,1)
print(a)
b=np.arange(3)
print(b)
print(a+b)

[[0]
 [1]
 [2]]
[0 1 2]
[[0 1 2]
 [1 2 3]
 [2 3 4]]
